# =============================================================
# KONFIGURASI SITUS FORUM ASN INKLUSIF
# =============================================================

title: "Forum ASN Inklusif"
email: contact@asninklusif.or.id
description: >- # Deskripsi ini akan muncul di Google Search
  Wadah sinergi, advokasi, dan pengembangan kapasitas Aparatur Sipil Negara (ASN) 
  penyandang disabilitas dan non-disabilitas untuk mewujudkan birokrasi Indonesia yang inklusif.
baseurl: "" 
url: "https://www.asninklusif.or.id" 

# --- PENGATURAN PENULIS (DEFAULT) ---
author:
  name: "Tim Redaksi ASN Inklusif"
  email: "contact@asninklusif.or.id"

# --- PENGATURAN BUILD & PAGINATION ---
markdown: kramdown
theme: minima 

# Pengaturan Halaman (Pagination)
paginate: 5                  # Menampilkan 5 artikel per halaman
paginate_path: "/page:num/"  # Link halaman berikutnya akan jadi /page2/, /page3/ dst

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap 
  - jekyll-paginate          # <--- Plugin Wajib untuk Pagination

# --- NAVIGASI HEADER (Menu Utama) ---
header_pages:
  - index.md
  - about.md
  - program.md
  - library.md
  - join.md

# --- SOCIAL MEDIA (Untuk Footer) ---
twitter_username: asninklusif 
instagram_username: asninklusif.id
github_username:  asninklusif

# --- AKSESIBILITAS & LOKALISASI ---
lang: id
timezone: Asia/Jakarta
